# Generated by Django 5.1.2 on 2024-10-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_created_at_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='posts', to='posts.comment'),
        ),
    ]
